spring:
  application:
    name: provider-cluster # 注册到EurekaServer上的名字
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true # 将IP注册到EurekaServer上
---
spring:
  profiles: cluster1 # 指定profile名字
server:
  port: 6007
---
spring:
  profiles: cluster2 # 指定profile名字
server:
  port: 6008
---
# 需要在 Run/Debug Configurations 中的 Programming Options 配置 --spring.profiles.active= XX
# XX就是application.yml中的spring.profiles