server:
  port: 6014
spring:
  application:
    name: hystrix-turbine # 注册到EurekaServer上的名字
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
  instance:
    prefer-ip-address: true # 将IP注册到EurekaServer上
turbine:
  app-config: consumer-hystrix
  instanceUrlSuffix:
      default: actuator/hystrix.stream